using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarsHr.Api.Domain.Entities;

public class User
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Unique login for authentication. Required for login form (1.1).
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string Login { get; set; } = string.Empty;

    /// <summary>
    /// Hashed password (using BCrypt / ASP.NET Identity or similar).
    /// Never store plain text. Used in AuthController + JWT flow (first day task for Анвар).
    /// </summary>
    [Required]
    public string PasswordHash { get; set; } = string.Empty;

    [MaxLength(200)]
    public string FullName { get; set; } = string.Empty;

    [MaxLength(150)]
    [EmailAddress]
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// User role. Possible values from ER diagram and TZ:
    /// "Administrator", "HR" (Отдел кадров), "DecisionMaker" (Решала).
    /// 
    /// Implications: 
    /// - Administrator: full access, user management (1.11).
    /// - HR: create/edit candidates, interviews, evaluations, competency matrix (1.7, 4.3-4.6).
    /// - DecisionMaker: view + final decision on candidate (4.8).
    /// 
    /// Can be extended later with claims/permissions for "Настройка прав" (1.3).
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string Role { get; set; } = "HR";

    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Timestamp of creation (timestamptz in PostgreSQL).
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Last successful login timestamp. Useful for security audit and "last activity".
    /// </summary>
    public DateTime? LastLoginAt { get; set; }

    // ============================================
    // NAVIGATION PROPERTIES (EF Core relationships)
    // ============================================

    /// <summary>
    /// Candidates created by this user (HR/Admin).
    /// Inverse of Candidate.CreatedBy.
    /// </summary>
    public ICollection<Candidate> CreatedCandidates { get; set; } = new List<Candidate>();

    /// <summary>
    /// Vacancies created by this user.
    /// </summary>
    public ICollection<Vacancy> CreatedVacancies { get; set; } = new List<Vacancy>();

    /// <summary>
    /// Interviews created (card started) by this user.
    /// </summary>
    public ICollection<Interview> CreatedInterviews { get; set; } = new List<Interview>();

    /// <summary>
    /// Interviews where this user is the interviewer.
    /// </summary>
    public ICollection<Interview> ConductedInterviews { get; set; } = new List<Interview>();

    /// <summary>
    /// Evaluations (competency scores) performed by this user.
    /// </summary>
    public ICollection<Evaluation> Evaluations { get; set; } = new List<Evaluation>();

    /// <summary>
    /// Final decisions made by this user (as "Решала").
    /// </summary>
    public ICollection<Decision> Decisions { get; set; } = new List<Decision>();

    /// <summary>
    /// Audit log entries performed by this user.
    /// </summary>
    public ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    /// <summary>
    /// Documents (PDFs) generated by this user.
    /// </summary>
    public ICollection<GeneratedDocument> GeneratedDocuments { get; set; } = new List<GeneratedDocument>();

    /// <summary>
    /// Applications (отклики) registered by this user.
    /// </summary>
    public ICollection<Application> RegisteredApplications { get; set; } = new List<Application>();
}
